import Head from 'next/head'
import Image from 'next/image'
import { Heading, Text } from '@ui-ignite/react'
import { Container, Hero, Preview } from './styles'

import calendarImg from '../../assets/calendar.png'
import bgHero from '../../assets/bg-hero.png'
import { ClaimUsernameForm } from './components/ClaimUsernameForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Ignite Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Image src={bgHero} alt="" fill />
        <Hero>
          <Heading as="h1" size="4xl">
            Agendamento Descomplicado
          </Heading>
          <Text size="xl">
            Conecte seu calendário e permita que as pessoas marquem agendamentos
            no seu tempo livre.
          </Text>
          <ClaimUsernameForm />
        </Hero>
        <Preview>
          <Image
            src={calendarImg}
            alt="Imagem de um Calendário simbolizando a aplicação"
            height={442}
            quality={100}
            priority
          />
        </Preview>
      </Container>
    </>
  )
}
