import Head from 'next/head'
import { Button, Heading, MultiStep, Text } from '@ui-ignite/react'
import { signIn } from 'next-auth/react'
import { Container, Header } from '../styles'
import { ArrowRight } from '@phosphor-icons/react'
import { ConnectBox, ConnectItem } from './styles'

export default function ConnectCalendar() {
  return (
    <>
      <Head>
        <title>Registro | Ignite Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Header>
          <Heading as="strong">Conecte sua agenda!</Heading>
          <Text>
            Conecte o seu calendário para verificar automaticamente as horas
            ocupadas e os novos eventos à medida em que são agendados.
          </Text>
          <MultiStep size={4} currentStep={2} />
        </Header>

        <ConnectBox>
          <ConnectItem>
            <Text>Google Calendar</Text>
            <Button
              variant="secondary"
              size="sm"
              onClick={() => signIn('google')}
            >
              Conectar <ArrowRight />
            </Button>
          </ConnectItem>
          <Button>
            Próximo passo
            <ArrowRight />
          </Button>
        </ConnectBox>
      </Container>
    </>
  )
}
